name: Release extension
on:
  push:
    tags:
      - "*"

jobs:
  publish-extension:
    name: Build extension and push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release extension
        run: TAG=${GITHUB_REF#refs/*/} make release-extension
        env:
          DOCKER_BUILDKIT: 1
